spring.application.name=demo

spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.jadira.usertype.autoRegisterUserTypes=true

#logging.level.root=DEBUG

spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=data/changelog/db.changelog-master.xml

security.jwt.secret-key=Zh8GgYjjnOgGwU53VLeJehXSVw5nYY5ktMKyl0hbsVs=
# 1h in millisecond
security.jwt.expiration-time=3600000